# If you just need a quick backend for your Symfony application, the only
# configuration you need is the list of entities:
#
# easy_admin:
#     entities:
#         - AppBundle\Entity\Category
#         - AppBundle\Entity\Image
#         - AppBundle\Entity\Purchase
#         - AppBundle\Entity\PurchaseItem
#         - AppBundle\Entity\Product

# This demo application is prepared to showcase most of the EasyAdmin features.
# That's why the backend configuration is much more detailed. All these options
# are explained in detail in the bundle documentation, which is published at
# https://github.com/javiereguiluz/EasyAdminBundle
easy_admin:
    site_name: 'ACME Backend'
    design:
        form_theme:   ['VichUploaderBundle:Form:fields.html.twig', 'EasyAdminBundle:form:bootstrap_3_horizontal_layout.html.twig']
        color_scheme: 'dark'
        assets:
            css:
                - '/bundles/app/stylesheets/demo.css'
        menu:
            - label: 'Products'
              icon: 'shopping-basket'
              children:
                  - { entity: 'Product', icon: 'th-list', label: 'List Products', params: { sortField: 'createdAt' } }
                  - { entity: 'Category', icon: 'tags' }
                  - { entity: 'Product', icon: 'plus-circle', label: 'Add Product', params: { action: 'new' } }
            - { label: 'Customers', entity: 'User', icon: 'users' }
            - { label: 'Purchases', entity: 'Purchase', icon: 'credit-card', params: { sortField: 'deliveryDate' } }
            - { label: 'About EasyAdmin' }
            - { label: 'Project Home', url: 'https://github.com/javiereguiluz/EasyAdminBundle', icon: 'home' }
            - { label: 'Documentation', url: 'https://github.com/javiereguiluz/EasyAdminBundle#getting-started-guide', icon: 'book' }
            - { label: 'Report Issues', url: 'https://github.com/javiereguiluz/EasyAdminBundle/issues', icon: 'github' }
    entities:
        Product:
            class: AppBundle\Entity\Product
            label: 'Products'
            list:
                fields:
                    - id
                    - enabled
                    - name
                    - { property: 'price', format: '%.2f' }
                    - { property: 'ean', label: 'EAN13', type: 'string' }
                    - { property: 'image', type: 'image', base_path: %app.path.product_images% }
                    - { property: 'createdAt', format: 'j / M / Y' }
                    - tags
            show:
                fields:
                    - id
                    - name
                    - { property: 'ean', label: 'EAN', type: 'string' }
                    - description
                    - { property: 'image', type: 'image', base_path: %app.path.product_images% }
                    - price
                    - features
                    - categories
                    - enabled
                    - createdAt
            form:
                fields:
                    - name
                    - { property: 'price', type: 'number' }
                    - { property: 'ean', label: 'EAN', help: 'EAN-13 valid code. Leave empty if unknown.' }
                    - { property: 'imageFile', type: 'Vich\UploaderBundle\Form\Type\VichImageType' }
                    - features
                    - categories
                    - enabled
                    - { property: 'description', type: 'Ivory\CKEditorBundle\Form\Type\CKEditorType' }
                    - createdAt
        User:
            class: AppBundle\Entity\User
            label: 'Users'
            list:
                fields: ['id', 'isActive', 'username', 'email', 'purchases', { property: 'contract', template: 'contract', base_path: %app.path.user_contracts% }]
            show:
                fields: ['id', 'isActive', 'username', 'email', 'purchases', { property: 'contract', template: 'contract', base_path: %app.path.user_contracts% }]
            edit:
                fields: ['username', 'email', 'isActive', 'purchases', { property: 'contractFile', type: 'Vich\UploaderBundle\Form\Type\VichFileType' }]
        Category:
            class: AppBundle\Entity\Category
            label: 'Categories'
            new:
                fields:
                    - 'name'
                    - { property: 'parent', type_options: { placeholder: 'Select a category...' } }
            list:
                title: 'Product %%entity_name%%'
                fields:
                    - 'id'
                    - { property: 'name', label: 'Label' }
                    - { property: 'parent', label: 'Parent category' }
                    - 'products'
        Purchase:
            class: AppBundle\Entity\Purchase
            label: 'Purchases'
            list:
                fields: ['guid', 'deliveryDate', 'deliveryHour', 'billingAddress', 'purchasedItems', 'total']
        PurchaseItem:
            class: AppBundle\Entity\PurchaseItem
            label: 'Purchase Items'
