easy_admin:
    site_name: 'ACME Backend'
    design:
        form_theme:   'horizontal'
        color_scheme: 'dark'
    entities:
        Category:
            class: AppBundle\Entity\Category
            label: 'Categories'
        Image:
            class: AppBundle\Entity\Image
            label: 'Images'
        Purchase:
            class: AppBundle\Entity\Purchase
            label: 'Purchases'
        PurchaseItem:
            class: AppBundle\Entity\PurchaseItem
            label: 'Purchase Items'
        Product:
            class: AppBundle\Entity\Product
            label: 'Products'
            list:
                fields:
                    - id
                    - name
                    - { property: 'price', format: '%.2f' }
                    - { property: 'ean', label: 'EAN13', type: 'string' }
                    - enabled
                    - { property: 'createdAt', format: 'j / M / Y' }
                    - tags
            show:
                fields:
                    - id
                    - name
                    - { property: 'ean', type: 'string' }
                    - description
                    - price
                    - features
                    - enabled
                    - createdAt
            form:
                fields:
                    - 'name'
                    - { property: price, type: 'number', help: 'Prices are always in euros' }
                    - { property: 'ean', label: 'EAN', help: 'EAN 13 valid code. Leave empty if unknown.' }
                    - 'enabled'
                    - 'description'
