_homepage:
    path: /
    defaults: { _controller: FrameworkBundle:Redirect:redirect, route: admin, permanent: true }

easy_admin_bundle:
    resource: @AppBundle/Controller/AdminController.php
    type:     annotation
    prefix:   /admin
