# This file sets the configuration of the 'User' entity.
#
# NOTE: this demo application splits the backend configuration into several
# small files for educational purposes. In your application you can put the
# entire backend configuration in just one file.
#
# The configuration options are explained in detail in the bundle documentation,
# which is published at https://github.com/javiereguiluz/EasyAdminBundle
easy_admin:
    entities:
        User:
            class: AppBundle\Entity\User
            list:
                title: 'Customers'
                actions: ['-new']
                fields: ['id', 'isActive', 'username', 'email', 'purchases', { property: 'contract', template: 'contract.html.twig', base_path: '%app.path.user_contracts%' }]
            show:
                fields: ['id', 'isActive', 'username', 'email', 'purchases', { property: 'contract', template: 'contract.html.twig', base_path: '%app.path.user_contracts%' }]
            form:
                fields:
                    - { type: 'group', label: 'Account Information', icon: 'user', css_class: 'col-sm-4' }
                    - { property: 'username' }
                    - { property: 'isActive' }
                    - { type: 'group', label: 'Contact Information', icon: 'envelope-o', css_class: 'col-sm-4' }
                    - { property: 'email' }
                    - { type: 'group', label: 'Legal Information', icon: 'briefcase', css_class: 'col-sm-4' }
                    - { property: 'contractFile', type: 'Vich\UploaderBundle\Form\Type\VichFileType' }
                    - { type: 'group', label: 'Transactions History', icon: 'money', css_class: 'col-sm-12' }
                    - { property: 'purchases', css_class: 'col-sm-12' }
