homepage:
    path: /
    defaults:
        _controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction
        route: easyadmin
        permanent: true

backend:
    resource: '../src/Controller/AdminController.php'
    prefix: /admin
    type: annotation
