# This file sets the configuration options related to the backend design.
# If your backend is simple, you probably can rely on the default values of
# the options and just define the value of the 'site_name' option.
#
# NOTE: this demo application splits the backend configuration into several
# small files for educational purposes. In your application you can put the
# entire backend configuration in just one file.
#
# The configuration options are explained in detail in the bundle documentation,
# which is published at https://github.com/javiereguiluz/EasyAdminBundle
easy_admin:
    site_name: 'ACME Backend'
    design:
        assets:
            css:
                - '/stylesheets/demo.css'
        form_theme:
            - '@EasyAdmin/form/bootstrap_4.html.twig'
            - '@FOSCKEditor/Form/ckeditor_widget.html.twig'
